### ISSUE TITLE
Create static Fees page using new design

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#11]
### User story
As Loconomics we want our Fees page to have an easy-to-read format to encourage users to understand what they're agreeing to.

#### Tasks
- [x] Create responsive html using Bootstrap 4 and this mockup:
- (awaiting @christinnolasco)
- [x] Implement CSS with Loconomics brand colors
- [x] Upload necessary assets

**Comment by tkwok** [comment]
I believe there's a better way to present fees to viewer than this mock. We can discuss options @joshdanielson

**Comment by joshdanielson** [comment]
@IagoSRL I updated this to use the terms photo. We won't have a link to this on the footer but will likely link to it in the app somewhere (TBD).
