### ISSUE TITLE
Create new Help page using new template

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#14]
### User story
As Loconomics we want our Help page to have an easy-to-read format so users can find the help they need.
#### Tasks
- [x] Create responsive html using Bootstrap 4 and this mockup:
![help](https://user-images.githubusercontent.com/1202838/44880067-391f7180-ac60-11e8-9961-0e9e9899014a.jpg)

- [x] Implement CSS with Loconomics brand colors
- [x] Upload necessary assets
![istock-918898950](https://user-images.githubusercontent.com/1202838/44880094-463c6080-ac60-11e8-9da2-c0f0ca125c1b.jpg)

**Comment by IagoSRL** [comment]
Content for this section should be static (included in the source code) or should be dynamic (getting it from Zendesk, as done now at https://loconomics.com/#!/help)?

**Comment by joshdanielson** [comment]
@IagoSRL we decided to keep this page static leaving the more "app" related questions to ZenDesk. So on this page, it will be just focused on answering questions about signing up.

**Comment by IagoSRL** [comment]
@joshdanielson Do you have the content to be included here or do you prefer to edit it yourself? Would be some kind of link for more content / other questions directed to our Zendesk for the rest of the content?

**Comment by joshdanielson** [comment]
@iagosrl I may have a draft somewhere but the idea is just a simple FAQ about joining so no zen desk. We’ll keep zendesk for the app, though. So just placeholders for now.

**Comment by IagoSRL** [comment]
Styles, markup, js implemented, but with placeholders. @joshdanielson  I assigned you to put the final content

**Comment by joshdanielson** [comment]
@IagoSRL pushed content to the page.
