### ISSUE TITLE
Create /pages/higher-education landing page

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#15]
- design (@christinnolasco please upload):

- image: 
![istock-908952856](https://user-images.githubusercontent.com/1202838/45057243-f5ef4500-b049-11e8-9632-21e642010d7b.jpg)

**Comment by christinnolasco** [comment]
![9 4 18 landing page - higher education](https://user-images.githubusercontent.com/39779527/45057510-a4938580-b04a-11e8-8527-0b0f2b8adaee.jpg)

**Comment by christinnolasco** [comment]
**Landing Page Logos**
[Landing Page Logos.zip](https://github.com/loconomics/loconomics-pages/files/2350246/Landing.Page.Logos.zip)
