### ISSUE TITLE
Create Sign-up and Log-in URLs

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#23]
For Sign-up buttons across all of loconomics-pages, we will direct users to:
https://www.loconomics.coop/sign_up?from=https%3A%2F%2Fwww.loconomics.com%2F%3F + buttonID + ID#

For Sign-in, go to normal: https://loconomics.com/#!/login

**Comment by IagoSRL** [comment]
This is done as our last conversation at Slack:
- sign up -> coop
- sign in -> coop
- additional navbar link 'toolkit' -> webapp dashboard

URLs to coop include a 'button_id' query parameter with values:
- 'NAV' for ones at the top global navbar
- for the 'become founding member' buttons:
  - 'HOME_MEMBER_OWNED' for link at the 'why a cooperative' section
  - 'HOME_HERO' for link on the top hero section
