### ISSUE TITLE
Add remaining testimonials to home page and videos

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#24]
Remaining testimonials:
- [x] Anahi
- [x] Christopher

Add videos ( on the right part of the testimonial)
- [x] Yavette 

`<iframe width="640" height="564" src="https://player.vimeo.com/video/308582814" frameborder="0" allowFullScreen mozallowfullscreen webkitAllowFullScreen></iframe>`

- [x] Christopher

`<iframe width="640" height="564" src="https://player.vimeo.com/video/308583445" frameborder="0" allowFullScreen mozallowfullscreen webkitAllowFullScreen></iframe>`

- [x] Anahi

`<iframe width="640" height="564" src="https://player.vimeo.com/video/308582962" frameborder="0" allowFullScreen mozallowfullscreen webkitAllowFullScreen></iframe>`

**Comment by IagoSRL** [comment]
@joshdanielson  At the branch `is24-testimonial-videos` there are the videos attached and design. But found lately that on shrinking the design fails so will look for another solution (will be later).

**Comment by joshdanielson** [comment]
@IagoSRL I see what you mean...it's close though!

**Comment by IagoSRL** [comment]
Pushed layout changes, fixing narrow sizes and aligned to center on large sizes, better spacing with buttons.
I merged it into *master* and closed this issue branch, so check it there.

**Comment by IagoSRL** [comment]
Just one note: I tried to disable the 'related videos' when finishing watching an embedded video, but seems that on Vimeo that's a premium option :-/
Not a big deal, but looked better without that (the usual 'rel=0' on Youtube).

**Comment by IagoSRL** [comment]
Added new Anahi's photo and optimized 'bio' images.
@joshdanielson I left original ratio and centering on photos, feel free to adjust them (some are off-centered, I suppose on purpose because of some "photo effect"), but they get cut not as good on narrow sizes.
