### ISSUE TITLE
Revisions for Marketing

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#28]
@IagoSRL I'd like to make the following tweaks to the main navigation:
- [x] Remove "About Us" (they can still click on it from the footer)
- [x] Move "Sign Up" and "Sign In" to the right
- [x] Make "Sign Up" a button with the brand-secondary color and change button text to "Join 90 Days Free" (you can leave the button text for the mobile nav as "Sign up")

Then revise the remaining buttons with:
- [x] Change button text from "Become Founding Member" to "Join 90 Days Free"
Add Google Analytics event tracking:
- [x] videos:
Main video: `ga('send', {
  hitType: 'event',
  eventCategory: 'Videos',
  eventAction: 'play',
  eventLabel: 'learn_more_loconomics_long' 
});` 

Testimonial videos: `ga('send', {
  hitType: 'event',
  eventCategory: 'Videos',
  eventAction: 'play',
  eventLabel: 'testminonial_yavette' or 'testimonial_christopher' or 'testimonial_anahi' 
});` 

- [x] buttons:
`ga('send', {
  hitType: 'event',
  eventCategory: 'Buttons',
  eventAction: 'join_90_days_free',
  eventLabel: 'nav' or 'hero' or 'whyCoop' or 'getInvolved' 
});` 

- [x] And also add a Facebook pixel to the <head> tag (edit to see code): 
`
<script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '598211963942244');
  fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=598211963942244&ev=PageView&noscript=1"
/></noscript>

`

**Comment by IagoSRL** [comment]
@joshdanielson I implemented and pushed this, while couldn't still check everything is working.

Note that I have to update the GA code for the new GTags.
There are some difficulties tracking when 'playing' videos, since content is in an iframe, had to load the Vimeo Player library but have to test when release ends.

Regarding the email about FBPixel, that I did before know about this issue (didn't get an email notice for some reason), so I updated the code to send not a URL but the same `eventLabel` as for Google Tags, so both systems should track when Coop buttons are clicked.

**Comment by IagoSRL** [comment]
Found some issues, fixed and pushed version (is deploying)

**Comment by joshdanielson** [comment]
@iagosrl thank you! Just tested it on live and a couple things:
- now thinking having the button in the mobile nav is too much. Can we have it just in large screens only? (Same breakpoint as the mobile nav
- the button under the first video still needs changing to “Join 90 Days Free”

**Comment by IagoSRL** [comment]
@joshdanielson I pushed that last details on master. Closing
