### ISSUE TITLE
Create static  Accessibility Policy page using new design

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#8]
### User story
As Loconomics we want our Accessibility Policy page to have an easy-to-read format to encourage users to understand what they're agreeing to.

#### Tasks
- [x] Create responsive html using Bootstrap 4 and this mockup:
- (awaiting @christinnolasco)
- [x] Implement CSS with Loconomics brand colors
- [x] Upload necessary assets

**Comment by IagoSRL** [comment]
Ready to be closed @joshdanielson?

**Comment by joshdanielson** [comment]
Yes, closing
